// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfWUdkYeBv-9Lano9OhHijHUO29CkSDe8',
    appId: '1:239199871265:web:e2babfe983ec66574a1e60',
    messagingSenderId: '239199871265',
    projectId: 'grocerystore-b0d25',
    authDomain: 'grocerystore-b0d25.firebaseapp.com',
    storageBucket: 'grocerystore-b0d25.firebasestorage.app',
    measurementId: 'G-7CSFSR3P6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZkk8wp5J9d4WW8QxMo-Rofl2DKwcayW4',
    appId: '1:239199871265:android:ab4252b99f2639034a1e60',
    messagingSenderId: '239199871265',
    projectId: 'grocerystore-b0d25',
    storageBucket: 'grocerystore-b0d25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjWY6Zt5ZXK5ak2cG0Dj4JcmcKMF1DPAo',
    appId: '1:239199871265:ios:40d461153ca1ab8b4a1e60',
    messagingSenderId: '239199871265',
    projectId: 'grocerystore-b0d25',
    storageBucket: 'grocerystore-b0d25.firebasestorage.app',
    iosBundleId: 'com.example.groceryStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjWY6Zt5ZXK5ak2cG0Dj4JcmcKMF1DPAo',
    appId: '1:239199871265:ios:40d461153ca1ab8b4a1e60',
    messagingSenderId: '239199871265',
    projectId: 'grocerystore-b0d25',
    storageBucket: 'grocerystore-b0d25.firebasestorage.app',
    iosBundleId: 'com.example.groceryStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfWUdkYeBv-9Lano9OhHijHUO29CkSDe8',
    appId: '1:239199871265:web:83d332ce54beddc44a1e60',
    messagingSenderId: '239199871265',
    projectId: 'grocerystore-b0d25',
    authDomain: 'grocerystore-b0d25.firebaseapp.com',
    storageBucket: 'grocerystore-b0d25.firebasestorage.app',
    measurementId: 'G-3K3FN7RVZ3',
  );
}
